#!/bin/bash

powerprofilesctl set latency-performance

MANGOHUD=1 gamemoderun gamescope \
    -w 2560 -h 1440 -r 88 -o 88 -f \
    --adaptive-sync \
    --immediate-flips \
    --rt \
    --force-grab-cursor \
    --mangoapp \
    -- \
    env \
    MANGOHUD_CONFIG="fps_limit=88,no_display" \
    PROTON_USE_FSYNC=1 \
    ENABLE_LAYER_MESA_ANTI_LAG=1 \
    game-performance "$@"

powerprofilesctl set power-saver